# Actor-Critic Configuration File

episodes: 500         # Number of training episodes
max_steps: 200        # Maximum steps per episode
learning_rate: 0.001  # Learning rate for the optimizer
gamma: 0.99           # Discount factor for future rewards
value_loss_coef: 0.5  # Coefficient for critic (value) loss
