# DQN Configuration File

episodes: 500            # Number of training episodes
max_steps: 200           # Maximum steps per episode
learning_rate: 0.001     # Learning rate for the optimizer
gamma: 0.99              # Discount factor for future rewards
batch_size: 64           # Batch size for sampling
epsilon_start: 1.0       # Starting epsilon value for epsilon-greedy
epsilon_end: 0.01        # Minimum epsilon value
epsilon_decay: 0.995     # Decay rate for epsilon per episode
memory_size: 10000       # Capacity of the replay buffer
update_target_every: 10  # Frequency to update the target network (in episodes)
gradient_clip: 1.0       # Maximum gradient clipping value
