# PG (Policy Gradient) Configuration File

episodes: 500         # Number of training episodes
max_steps: 200        # Maximum number of steps per episode
learning_rate: 0.001  # Learning rate for the optimizer
gamma: 0.99           # Discount factor for future rewards
